# Generated by Django 4.0.3 on 2022-04-09 13:20

from django.db import migrations, models
import phonenumber_field.validators


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='phone_no',
            field=models.CharField(max_length=15, unique=True, validators=[phonenumber_field.validators.validate_international_phonenumber]),
        ),
    ]
